# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7fa761e5c145d2b72caa81c8ea1330540f64192b632b3ef1b2779db07bdcc0013b8faa2a11dcaab0a978fd3169f8d82880e78658eb487146909a224461ab0f0e

test:
  secret_key_base: acf63f374c6ae481a0b45ace772e5de5ea6005f1bac6315a6c65465337c0963b48268a59be1ec0903d9b5a07c033fac376d2fb53ce0dd48f45b283462aad2f17

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
